# Generated by Django 4.2.2 on 2023-06-21 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='Comentario',
            new_name='comment',
        ),
    ]
