# Generated by Django 4.2.2 on 2023-06-21 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_rename_comentario_comentario_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='data',
            new_name='date',
        ),
    ]
