# Generated by Django 4.2.2 on 2023-06-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto_turistico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
