# Generated by Django 4.2.2 on 2023-06-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
        ('ponto_turistico', '0002_alter_pontoturistico_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='attraction',
            field=models.ManyToManyField(to='atracoes.atracao'),
        ),
    ]
