# Generated by Django 4.2.2 on 2023-06-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('ponto_turistico', '0003_pontoturistico_attraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='comment',
            field=models.ManyToManyField(to='comentarios.comentario'),
        ),
    ]
