# Generated by Django 4.2.2 on 2023-06-20 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localizacoes', '0001_initial'),
        ('ponto_turistico', '0005_pontoturistico_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='placement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='localizacoes.localizacao'),
            preserve_default=False,
        ),
    ]
